security:
  basic:
    enabled: false
  # Facebook
  oauth2:
    client:
      clientId: ${facebookClientId}
      clientSecret: ${facebookSecret}
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
  # Google
  oauth2:
    client:
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientId: ${googleClientId}
      clientSecret: ${googleSecret}
      scope: email
    resource:
      jwt.keyUri:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo