security:
  basic:
    enabled: false
  # Facebook
#  oauth2:
#    client:
#      clientId: 864908383978705
#      clientSecret: fb7a6f636097f343b5b4c09e9e3fd4d1
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me
  # Google
  oauth2:
    client:
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientId: 249012168798-l8ojq56i9jliudv7o2qfog24gcjhnd4m.apps.googleusercontent.com
      clientSecret: rRTu2UVxc-3Z4QZS6MwcHeUO
      scope: email
    resource:
      jwt.keyUri:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
#  oauth2:
#    client:
#      registration:
#        google:
#          accessTokenUri: https://accounts.google.com/o/oauth2/token
#          userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#          clientId: 249012168798-l8ojq56i9jliudv7o2qfog24gcjhnd4m.apps.googleusercontent.com
#          clientSecret: rRTu2UVxc-3Z4QZS6MwcHeUO
#          redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#          scope:
#            - email
#            - profile
#        facebook:
#          clientId: 864908383978705
#          clientSecret: fb7a6f636097f343b5b4c09e9e3fd4d1
#          redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" # Note that facebook now mandates the use of https redirect URIs, so make sure your app supports https in production
#          scope:
#            - email
#            - public_profile